### ISSUE TITLE
IPN on Sandbox mode

### ISSUE THREAD

**Issue by pablomusumeci** [kauplus/mercadopago#15]
Hi guys, I was wondering if your gem can be used in sandbox mode when I'm doing a GET request with my purchase ID to the IPN system.

Because when I'm excuting mp.notification(@payment_id), I get {"message"=>"Resource XXXXXXX not found", "error"=>"not_found", "status"=>404, "cause"=>[]} as response, but when I do the request manually pointing to https://api.mercadolibre.com/sandbox/collections/notifications/XXXXXXX' everything works as expected. (notice the /sandbox/)

Thanks!

**Comment by gulymaestro** [comment]
Done

**Comment by rafaelivan** [comment]
See #16
